### ISSUE TITLE
canOpenURL: failed for URL

### ISSUE THREAD

**Issue by dipsvaishnav** [sumup/sumup-ios-url-scheme#1]
-canOpenURL: failed for URL: "sumupmerchant://" - error: "This app is not allowed to query for scheme sumupmerchant"

**Comment by schneider-iosphere** [comment]
Please add the following to you Applications Info.plist:

```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>sumupmerchant</string>
</array>
```

**Comment by JohannesRu** [comment]
Hey, thanks for reaching out. If you build for iOS 9+ you probably want to set LSApplicationQueriesSchemes in your info.plist 
There is more info on the security feature here:
https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW14

**Comment by JohannesRu** [comment]
Hey, thanks for reaching out. You probably want to set LSApplicationQueriesSchemes in your info.plist

<key>LSApplicationQueriesSchemes</key>
<array>
    <string>sumupmerchat</string>
</array>

You can find more details in the docs
https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html%23//apple_ref/doc/uid/TP40009250-SW14

Let us know if the issue remains, hope I could help :-)

**Comment by dipsvaishnav** [comment]
*I got this error*

*-canOpenURL: failed for URL: "sumupmerchant://" - error: "(null)"*

*2016-07-12 13:42:30.724 SMPPaymentSampleApp[11934:433331] SumUp app is
installed: NO*

*2016-07-12 13:43:10.945 SMPPaymentSampleApp[11934:433331] request:
<SMPPaymentRequest:
0x7f9da05d3220>scheme://pay/1.0?amount=1.00&currency=EUR&affiliate-key=169f0ee2-bc0a-470f-8fac-f30c26d698da&title=the%20&callbackfail=samplepaymentapp%3A%2F%2F&callbacksuccess=samplepaymentapp%3A%2F%2F&receipt-email=dvaishnav750%40gmail.com
<http://40gmail.com>&foreign-tx-id=9587374676-33C8E985-6E44-48C0-B282-D156AB285E66-11934-00002F7F8725D3F1
:sumupmerchant://pay/1.0?amount=1.00&currency=EUR&affiliate-key=169f0ee2-bc0a-470f-8fac-f30c26d698da&title=the%20&callbackfail=samplepaymentapp%3A%2F%2F&callbacksuccess=samplepaymentapp%3A%2F%2F&receipt-email=dvaishnav750%40gmail.com
<http://40gmail.com>&foreign-tx-id=9587374676-33C8E985-6E44-48C0-B282-D156AB285E66-11934-00002F7F8725D3F1*

Deepak Kumar Vaishnav

On Tue, Jul 12, 2016 at 1:39 PM, Johannes Rupieper <notifications@github.com

**Comment by JohannesRu** [comment]
Thanks for the details. Can you confirm that in your info.plist you  added app query scheme "sumupmerchant" to LSApplicationQueriesSchemes  as shown in my previous message?

**Comment by dipsvaishnav** [comment]
Yes

Deepak Kumar Vaishnav

On Tue, Jul 12, 2016 at 1:47 PM, Johannes Rupieper <notifications@github.com

**Comment by dipsvaishnav** [comment]
Deepak Kumar Vaishnav

**Comment by dipsvaishnav** [comment]
can u give me Skype id please

Deepak Kumar Vaishnav
