### ISSUE TITLE
Does this url scheme support 3G?

### ISSUE THREAD

**Issue by nam-truong-le** [sumup/sumup-ios-url-scheme#12]
Hi,

I have a web application for my local store. The app generates this URL scheme. The forwarding to SumUp iOS app is working well but after that, the iOS app cannot send the payment request to the terminal. I have an 3G terminal. Does this work only with Air terminal?

Many Thanks
Nam Truong Le

**Comment by floschliep** [comment]
Hi @nam-truong-le, 

yes, this will only work with an Air terminal. For more information and available options for your integration, I recommend to get in touch with the helpful folks at integration@sumup.com.
