### ISSUE TITLE
Pop-up post transaction

### ISSUE THREAD

**Issue by raphaels17** [sumup/sumup-ios-url-scheme#4]
Hi

Is there any way I can avoid  to have the popup post success of a transaction that suggest to send the receipt via email? This is consistent with our app experience.

Best regards 

Raphael

**Comment by mollidor** [comment]
Hi.

We are about to add support to skip the receipt screen (not aware of a popup) for successful transactions with an upcoming version of the app. We will update the documentation accordingly and let you know once it has been released.

Best,
Lukas

**Comment by mollidor** [comment]
Missed to close this one. See `skip-screen-success` in https://github.com/sumup/sumup-ios-url-scheme#optional-query-parameters
