### ISSUE TITLE
Is there anyway to emulate transactions to test sumup application integration?

### ISSUE THREAD

**Issue by ryaa** [sumup/sumup-ios-url-scheme#5]
For example, the mobile app launch the sumup app using sumup custom URL scheme, then I execute fake transaction without sumup device and then the sumup application trigger success callback (which will open the mobile app using my app custom URL scheme and navigate to the appropriate view)?
It seems that there is no way to do this without making a real transaction with the real device.

Thanks

**Comment by mollidor** [comment]
Hi @ryaa 

There is no such functionality atm. If you need to test your integration feel free to get in touch with integration@sumup.com and explain your setup. We'll do our best to get you started.

Regards,
Lukas
