### ISSUE TITLE
How about additional info? 

### ISSUE THREAD

**Issue by viccotr** [sumup/sumup-ios-url-scheme#6]
Hi, I see in android api:
            .addAdditionalInfo("AccountId", "taxi0334")
            .addAdditionalInfo("From", "Paris")
            .addAdditionalInfo("To", "Berlin")
Does api for iOS also can do it?

**Comment by mollidor** [comment]
Hi @viccotr,

this is currently not supported by the iOS API and we don't have immediate plans to add it. 
Feel free to drop an email to integration@sumup.com and explain your integration.

Regards,
Lukas
